### ISSUE TITLE
It doesn't work if the mouse cursor is not on the joystick.

### ISSUE THREAD

**Issue by saklanmazozgur** [shakram02/XamlVirtualJoystick#2]
Hello there,

The joystick is very nice in design and function, but if the mouse cursor is outside the joystick, the rotation process does not occur. How we can solve this problem.

Can it rotate with the same function outside of the joystick area?

**Comment by shakram02** [comment]
Hello, 

Thank you, sorry this function isn't supported as it was not required in the design.

Please feel free to fork the repo and apply the modifications you want as I don't work on this project any more.
